### ISSUE TITLE
Questions) About CSS

### ISSUE THREAD

**Issue by filoscoder** [filoscoder/fe-soon#1]
# **Questions** 
- [x] 동영상에서 보시는 것처럼 오른쪽에 빈 공간이 남습니다.(스크롤바 보시면 남는게 보여요.) 왜 이런걸까요?
- [ ] Footer에 오른쪽에 아이콘 넣어야 하는 곳들에 그냥 동그라미를 넣었는데 동그라미들이 찌그러지는데 왜 이런걸까요?
- [x] 사진 넣는 예시를 좀 받을 수 있을까요? 이런식의 다양한 구성을 많이 쓸 것 같습니다. 그냥 그리드로 넣은건가요? 비율이 좀 찌그러지거나 할 것같은데, 아니면 그냥 사진을 넣을때 특정한 비율로 맞춰서 넣는건가요?
* 사진 넣는 예시: https://www.wearecollins.com/work/

- [x] JavaScript도 그냥 바로 같이 가는게 나을까요?
- [x] BEM이 아직 조금 햇갈립니다.
- [x] x, 2x 개념 설명해주세요!

**Comment by filoscoder** [comment]
> 동영상에서 보시는 것처럼 오른쪽에 빈 공간이 남습니다.(스크롤바 보시면 남는게 보여요.) 왜 이런걸까요?
```CSS
body {
overflow:   hidden;
/* overflow-y: hidden; */
/* overflow-x: hidden; */
}

/*
::-webkit-scrollbar {
    width: 0px;
    background: transparent; 
}
*/

/*
::-webkit-scrollbar {
    display: none;
}
*/
```
